on:
  push:
    branches:
      - master
name: coverage
jobs:
  coveralls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 13
      - run: npm install
      - run: npm test
      - run: ./node_modules/.bin/c8 report --reporter=text-lcov | ./node_modules/.bin/coveralls
    env:
      COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
      COVERALLS_GIT_BRANCH: "${{ github.ref }}"
